from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeBattleSceneAssets: 


	# Image Rule Assets
	#  
	I_REWARD_1 = RuleImage(roi_front=(551,505,165,84), roi_back=(451,413,372,226), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattleScene/bs1/bs1_reward_1.png")


