from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class LootStatisticsAssets: 


	# Image Rule Assets
	# 突破卷 
	I_REALM_RAID_PASS = RuleImage(roi_front=(402,175,100,100), roi_back=(251,161,809,128), threshold=0.8, method="Template matching", file="./tasks/Component/LootStatistics/ls/ls_realm_raid_pass.png")


