from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class HyakkiyakouAssets:

	END = RuleImage(roi_front=(0, 0, 246, 78), roi_back=(0, 0, 1240, 700), threshold=0.8,
					method="Template matching",
					file="./tasks/Hyakkiyakou/res/end.png")
	START = RuleImage(roi_front=(1116, 556, 110, 85), roi_back=(0, 0, 1240, 700), threshold=0.8,
					 method="Template matching",
					 file="./tasks/Hyakkiyakou/res/start.png")


