from __future__ import annotations

"""GameUi 页面公共导出层。

外部任务统一继续从 `tasks.GameUi.page` 导入页面定义、页面模型和辅助组合器，
内部实现已经拆分到多个独立文件中。
"""

from tasks.GameUi.action import ActionSequence, ConditionalAction, conditional_action, sequence
from tasks.GameUi.default_pages import (
    page_act_list,
    page_area_boss,
    page_awake_zones,
    page_battle,
    page_battle_prepare,
    page_battle_result,
    page_bondling_fairyland,
    page_collection,
    page_daily,
    page_delegation,
    page_demon_encounter,
    page_demon_encounter_realworld,
    page_draft_duel,
    page_duel,
    page_entertainment,
    page_exploration,
    page_friends,
    page_goryou_realm,
    page_guild,
    page_heian_kitan,
    page_hero_test,
    page_hunt,
    page_hunt_kirin,
    page_hyakkiyakou,
    page_kekkai_toppa,
    page_login,
    page_main,
    page_mall,
    page_mall_recommend,
    page_onmyodo,
    page_realm_raid,
    page_reward,
    page_secret_zones,
    page_shikigami_records,
    page_six_gates,
    page_soul_zones,
    page_summon,
    page_team,
    page_town,
    page_travel,
    page_shirin,
    random_click,
    page_battle_team,
    page_battle_team_exit,
    page_pet
)
from tasks.GameUi.matcher import AllMatcher, AnyMatcher, AtomMatcher, Matcher, NotMatcher, all_of, any_of, ensure_matcher, not_
from tasks.GameUi.page_definition import Page, Transition
from tasks.GameUi.registry import PageRegistry

__all__ = [
    "ActionSequence",
    "AllMatcher",
    "AnyMatcher",
    "AtomMatcher",
    "ConditionalAction",
    "Matcher",
    "NotMatcher",
    "Page",
    "PageRegistry",
    "Transition",
    "all_of",
    "any_of",
    "conditional_action",
    "ensure_matcher",
    "not_",
    "page_act_list",
    "page_area_boss",
    "page_awake_zones",
    "page_battle",
    "page_battle_prepare",
    "page_battle_result",
    "page_bondling_fairyland",
    "page_collection",
    "page_daily",
    "page_delegation",
    "page_demon_encounter",
    "page_demon_encounter_realworld",
    "page_draft_duel",
    "page_duel",
    "page_entertainment",
    "page_exploration",
    "page_friends",
    "page_goryou_realm",
    "page_guild",
    "page_heian_kitan",
    "page_hero_test",
    "page_hunt",
    "page_hunt_kirin",
    "page_hyakkiyakou",
    "page_kekkai_toppa",
    "page_login",
    "page_main",
    "page_mall",
    "page_mall_recommend",
    "page_onmyodo",
    "page_realm_raid",
    "page_reward",
    "page_secret_zones",
    "page_shikigami_records",
    "page_six_gates",
    "page_soul_zones",
    "page_summon",
    "page_team",
    "page_town",
    "page_travel",
    "page_shirin",
    "random_click",
    "sequence",
    "page_battle_team",
    "page_battle_team_exit",
    "page_pet"
]
