from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class BingcangmijingAssets: 


	# Image Rule Assets
	# 兵藏秘境解锁阵容 
	I_BCMJ_UNLOCK = RuleImage(roi_front=(907,658,23,20), roi_back=(907,658,23,20), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_unlock.png")
	# 兵藏秘境锁定阵容 
	I_BCMJ_LOCK = RuleImage(roi_front=(907,658,23,20), roi_back=(907,658,23,20), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_lock.png")
	# 兵藏秘境开始战斗按钮 
	I_BCMJ_FIRE = RuleImage(roi_front=(1140,590,75,38), roi_back=(1140,590,75,38), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_fire.png")
	# 确认选择祝福 
	I_BCMJ_BUFF_CONFIRM = RuleImage(roi_front=(573,625,130,48), roi_back=(573,625,130,48), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_buff_confirm.png")
	# 选择局内祝福1 
	I_BCMJ_BUFF1_CLICK = RuleImage(roi_front=(44,119,20,488), roi_back=(44,119,20,488), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_buff1_click.png")
	# 选择局内祝福2 
	I_BCMJ_BUFF2_CLICK = RuleImage(roi_front=(345,118,20,490), roi_back=(345,118,20,490), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_buff2_click.png")
	# 选择局内祝福3 
	I_BCMJ_BUFF3_CLICK = RuleImage(roi_front=(651,120,20,488), roi_back=(651,120,20,488), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_buff3_click.png")
	# 选择局内祝福4 
	I_BCMJ_BUFF4_CLICK = RuleImage(roi_front=(953,121,20,486), roi_back=(953,121,20,486), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_buff4_click.png")
	# 重置兵藏秘境弹窗选确认 
	I_BCMJ_RESET_CONFIRM = RuleImage(roi_front=(685,411,147,41), roi_back=(685,411,147,41), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_reset_confirm.png")
	# 重置兵藏秘境弹窗选取消 
	I_BCMJ_RESET_CANCEL = RuleImage(roi_front=(442,412,156,44), roi_back=(442,412,156,44), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_reset_cancel.png")
	# 兵藏秘境每周提示确认 
	I_BCMJ_WEEKLY_CONFIRM = RuleImage(roi_front=(685,410,146,44), roi_back=(685,410,146,44), threshold=0.8, method="Template matching", file="./tasks/Bingcangmijing/bcmj/bcmj_bcmj_weekly_confirm.png")


	# Ocr Rule Assets
	# 兵道帖数量 
	O_BINGDAOTIE_COUNT = RuleOcr(roi=(735,24,85,31), area=(735,24,85,31), mode="DigitCounter", method="Default", keyword="", name="bingdaotie_count")
	# 兵道帖·机密数量 
	O_BINGDAOTIE_JIMI_COUNT = RuleOcr(roi=(965,25,44,29), area=(965,25,44,29), mode="Digit", method="Default", keyword="", name="bingdaotie_jimi_count")
	# 局内祝福升级1 
	O_BUFF_1 = RuleOcr(roi=(58,346,250,54), area=(58,346,250,54), mode="Single", method="Default", keyword="", name="buff_1")
	# 局内祝福升级2 
	O_BUFF_2 = RuleOcr(roi=(363,346,250,54), area=(363,346,250,54), mode="Single", method="Default", keyword="", name="buff_2")
	# 局内祝福升级3 
	O_BUFF_3 = RuleOcr(roi=(665,346,250,54), area=(665,346,250,54), mode="Single", method="Default", keyword="", name="buff_3")
	# 局内祝福升级4 
	O_BUFF_4 = RuleOcr(roi=(968,346,250,54), area=(968,346,250,54), mode="Single", method="Default", keyword="", name="buff_4")


