from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SwitchAccountAssets: 


	# Click Rule Assets
	# 账号下拉菜单 
	C_SA_LOGIN_FORM_DROPDOWN_BTN = RuleClick(roi_front=(470,280,350,100), roi_back=(470,280,350,100), name="sa_login_form_dropdown_btn")
	# 登录按钮 
	C_SA_LOGIN_FORM_LOGIN_BTN = RuleClick(roi_front=(535,420,240,60), roi_back=(535,420,240,60), name="sa_login_form_login_btn")
	# 登录界面-用户中心按钮默认位置 
	C_SA_LOGIN_FORM_USER_CENTER = RuleClick(roi_front=(1210,230,40,40), roi_back=(1210,230,40,40), name="sa_login_form_user_center")
	# 登录界面-切换服务器按钮 
	C_SA_LOGIN_FORM_SWITCH_SVR_BTN = RuleClick(roi_front=(550,510,280,35), roi_back=(550,510,280,35), name="sa_login_form_switch_svr_btn")
	# 登录界面-进入游戏按钮 
	C_SA_LOGIN_FORM_ENTER_GAME_BTN = RuleClick(roi_front=(570,580,130,35), roi_back=(570,580,130,35), name="sa_login_form_enter_game_btn")
	# 登录界面-选择服务器-底部账号信息展开后的区域 
	C_SA_LOGIN_FORM_CHARACTER_AREA = RuleClick(roi_front=(260,450,760,160), roi_back=(260,450,760,160), name="sa_login_form_character_area")
	# 登录界面-选择服务器-点击关闭选择服务器界面的空白区域 
	C_SA_LOGIN_FORM_CANCEL_SVR_SELECT = RuleClick(roi_front=(50,70,60,360), roi_back=(50,70,60,360), name="sa_login_form_cancel_svr_select")
	# 登录界面-用户中心-右上角关闭按钮 
	C_SA_LOGIN_FORM_USER_CENTER_CLOSE_BTN = RuleClick(roi_front=(1055,120,20,20), roi_back=(1055,120,20,20), name="sa_login_form_user_center_close_btn")
	# 登录界面-账号选择界面-右上角关闭按钮 
	C_SA_LOGIN_FORM_ACCOUNT_CLOSE_BTN = RuleClick(roi_front=(895,165,40,40), roi_back=(895,165,40,40), name="sa_login_form_account_close_btn")
	# 游戏庭院内 左上角 头像 
	C_SA_EG_PROFILE_PHOTO = RuleClick(roi_front=(35,35,55,55), roi_back=(35,35,55,55), name="sa_eg_profile_photo")
	# 选择服务器界面 底部角色名 列表---与ocr.json中同名对象区域一致 
	C_SA_SELECT_SVR_CHARACTER_LIST = RuleClick(roi_front=(205,570,815,40), roi_back=(205,570,815,40), name="sa_select_svr_character_list")


	# Ocr Rule Assets
	# 登录页面服务器名称 
	O_SA_LOGIN_FORM_SVR_NAME = RuleOcr(roi=(545,510,140,40), area=(545,510,140,40), mode="SINGLE", method="Default", keyword="", name="sa_login_form_svr_name")
	# 选择服务器界面 底部角色所属服务器名 列表 
	O_SA_SELECT_SVR_SVR_LIST = RuleOcr(roi=(205,540,815,25), area=(205,540,815,25), mode="FULL", method="Default", keyword="", name="sa_select_svr_svr_list")
	# 选择服务器界面 底部角色名 列表 
	O_SA_SELECT_SVR_CHARACTER_LIST = RuleOcr(roi=(205,570,815,40), area=(205,570,815,40), mode="FULL", method="Default", keyword="", name="sa_select_svr_character_list")
	# 选择账号界面 账号列表 
	O_SA_ACCOUNT_ACCOUNT_LIST = RuleOcr(roi=(460,280,440,330), area=(460,280,440,330), mode="FULL", method="Default", keyword="", name="sa_account_account_list")
	# 选择账号界面 已选择的账号 
	O_SA_ACCOUNT_ACCOUNT_SELECTED = RuleOcr(roi=(460,280,370,50), area=(460,280,370,50), mode="SINGLE", method="Default", keyword="", name="sa_account_account_selected")
	# 登录界面 用户中心(区别于游戏内用户中心) 账户名 
	O_SA_LOGIN_FORM_USER_CENTER_ACCOUNT = RuleOcr(roi=(290,185,290,50), area=(290,185,290,50), mode="SINGLE", method="Default", keyword="", name="sa_login_form_user_center_account")


	# Swipe Rule Assets
	# 登录界面 服务器列表的手指向左滑动 
	S_SA_SVR_SWIPE_LEFT = RuleSwipe(roi_front=(730,460,30,21), roi_back=(470,410,26,21), mode="default", name="sa_svr_swipe_left")
	# 登录界面 账号列表的手指向上滑动 
	S_SA_ACCOUNT_LIST_UP = RuleSwipe(roi_front=(600,520,30,20), roi_back=(750,270,30,20), mode="default", name="sa_account_list_up")


	# Image Rule Assets
	# 用于判断是否在登录界面的 
	I_CHECK_LOGIN_FORM = RuleImage(roi_front=(178,572,53,60), roi_back=(1,547,241,105), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/check_login_form.png")
	# 游戏内-点击头像弹出的设置界面-左侧-用户中心按钮 
	I_SA_USER_CENTER = RuleImage(roi_front=(190,390,330,200), roi_back=(190,390,330,200), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_user_center.png")
	# 游戏内-点击头像弹出的设置界面-顶部设置字样 
	I_SA_USER_CENTER_PROFILE = RuleImage(roi_front=(590,60,90,55), roi_back=(590,60,90,55), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_user_center_profile.png")
	# 游戏内点击用户中心后弹出的 切换用户按钮 
	I_SA_SWITCH_ACCOUNT_BTN = RuleImage(roi_front=(930,170,160,75), roi_back=(930,170,160,75), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_switch_account_btn.png")
	# 登录界面 已登录状态下 点击用户中心后弹出的对话框中 复制账号按钮 
	I_SA_USER_CENTER_COPY_BTN = RuleImage(roi_front=(460,280,640,50), roi_back=(460,280,640,50), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_user_center_copy_btn.png")
	# 登录界面-选取账号界面-顶部网易游戏LOGO 
	I_SA_NETEASE_GAME_LOGO = RuleImage(roi_front=(500,170,300,90), roi_back=(500,170,300,90), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_netease_game_logo.png")
	# 登录界面-选取账号界面-账号下拉菜单-关闭标志. 
	I_SA_ACCOUNT_DROP_DOWN_CLOSED = RuleImage(roi_front=(850,320,30,25), roi_back=(850,320,30,25), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_account_drop_down_closed.png")
	# 登录界面-选取账号界面-账号下拉菜单-添加新账号. 
	I_SA_ACCOUNT_DROP_DOWN_ADD_ACCOUNT = RuleImage(roi_front=(400,540,220,60), roi_back=(400,540,220,60), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_account_drop_down_add_account.png")
	# 登录界面-选取账号界面-账号下拉菜单-已经打开标志. 
	I_SA_ACCOUNT_LOGIN_BTN = RuleImage(roi_front=(400,400,480,90), roi_back=(400,400,480,90), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_account_login_btn.png")
	# 登录界面-选择手机类型为苹果. 
	I_SA_LOGIN_FORM_APPLE = RuleImage(roi_front=(490,350,100,100), roi_back=(490,350,100,100), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_login_form_apple.png")
	# 登录界面-选择手机类型为android 
	I_SA_LOGIN_FORM_ANDROID = RuleImage(roi_front=(690,350,100,100), roi_back=(690,350,100,100), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_login_form_android.png")
	# 判断是否在 选择服务器 界面的标志物 角色的服务器图标还未显示时 
	I_SA_CHECK_SELECT_SVR_1 = RuleImage(roi_front=(240,530,120,40), roi_back=(240,530,120,40), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_check_select_svr.png")
	# 判断是否在 选择服务器 界面的标志物 角色的服务器图标已经显示时 
	I_SA_CHECK_SELECT_SVR_2 = RuleImage(roi_front=(240,410,120,40), roi_back=(240,410,120,40), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchAccount/res/sa_check_select_svr.png")


