from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GuildActivityMonitorAssets: 


	# Ocr Rule Assets
	# 寮活动通知检测区域 
	O_GUILD_ACTIVITY_NOTIFY = RuleOcr(roi=(13,213,457,86), area=(13,213,457,86), mode="Full", method="Default", keyword="", name="guild_activity_notify")


