from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by module/dev_tools/assets_extract.py.
# Don't modify it manually.
class GlobalGameAssets: 


	# Image Rule Assets
	# description 
	I_ACCEPT = RuleImage(roi_front=(825,395,56,46), roi_back=(825,395,56,46), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/gg/gg_accept.png")
	# description 
	I_REJECT = RuleImage(roi_front=(825,493,53,51), roi_back=(825,493,53,51), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/gg/gg_reject.png")
	# 勾玉 
	I_JADE = RuleImage(roi_front=(661,466,43,46), roi_back=(661,466,43,46), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/gg/gg_jade.png")
	# 网络异常 
	I_NETWORK_ABNORMAL = RuleImage(roi_front=(583,330,221,67), roi_back=(583,330,221,67), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/gg/gg_network_abnormal.png")
	# 已端口游戏服务器，需要重新连接，这种情况一般是断开很久了 
	I_NETWORK_ERROR = RuleImage(roi_front=(431,253,416,208), roi_back=(431,253,416,208), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/gg/gg_network_error.png")
	# 我还没有碰到这个情况没能截图 
	I_CLIENT_CLEAR = RuleImage(roi_front=(578,369,151,72), roi_back=(578,369,151,72), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/gg/gg_client_clear.png")


