from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeBattleAssets: 


	# Image Rule Assets
	# 指针 
	I_LOCAL_1 = RuleImage(roi_front=(119,493,23,25), roi_back=(119,493,23,25), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle1/battle1_local_1.png")
	# 左上角退出 
	I_EXIT_1 = RuleImage(roi_front=(21,20,27,31), roi_back=(21,20,27,31), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle1/battle1_exit_1.png")
	# 左上角好友 
	I_FRIENDS_1 = RuleImage(roi_front=(88,18,35,34), roi_back=(88,18,35,34), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle1/battle1_friends_1.png")


	# Image Rule Assets
	# description 
	I_LOCAL_2 = RuleImage(roi_front=(30,569,21,22), roi_back=(30,569,21,22), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle2/battle2_local_2.png")
	# description 
	I_EXIT_2 = RuleImage(roi_front=(17,16,35,34), roi_back=(17,16,35,34), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle2/battle2_exit_2.png")
	# description 
	I_FRIENDS_2 = RuleImage(roi_front=(88,15,34,39), roi_back=(88,15,34,39), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle2/battle2_friends_2.png")


	# Image Rule Assets
	# 指针 
	I_LOCAL_3 = RuleImage(roi_front=(29,567,23,25), roi_back=(29,567,23,25), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle3/battle3_local_3.png")
	# 左上角退出 
	I_EXIT_3 = RuleImage(roi_front=(23,18,27,31), roi_back=(23,18,27,31), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle3/battle3_exit_3.png")
	# 左上角好友 
	I_FRIENDS_3 = RuleImage(roi_front=(89,17,35,34), roi_back=(89,17,35,34), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle3/battle3_friends_3.png")


	# Image Rule Assets
	# 指针 
	I_LOCAL_4 = RuleImage(roi_front=(29,567,23,25), roi_back=(29,567,23,25), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle4/battle4_local_4.png")
	# 左上角退出 
	I_EXIT_4 = RuleImage(roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle4/battle4_exit_4.png")
	# 左上角好友 
	I_FRIENDS_4 = RuleImage(roi_front=(88,16,35,34), roi_back=(88,16,35,34), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle4/battle4_friends_4.png")


	# Image Rule Assets
	# 指针 
	I_LOCAL_5 = RuleImage(roi_front=(30,567,23,25), roi_back=(30,567,23,25), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle5/battle5_local_5.png")
	# 左上角退出 
	I_EXIT_5 = RuleImage(roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle5/battle5_exit_5.png")
	# 左上角好友 
	I_FRIENDS_5 = RuleImage(roi_front=(90,17,35,34), roi_back=(90,17,35,34), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle5/battle5_friends_5.png")


	# Image Rule Assets
	# 指针 
	I_LOCAL_6 = RuleImage(roi_front=(30,566,23,25), roi_back=(30,566,23,25), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle6/battle6_local_6.png")
	# 左上角退出 
	I_EXIT_6 = RuleImage(roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle6/battle6_exit_6.png")
	# 左上角好友 
	I_FRIENDS_6 = RuleImage(roi_front=(89,18,35,34), roi_back=(89,18,35,34), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeBattle/battle6/battle6_friends_6.png")


