from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class LoginHarvestAssets: 


	# Image Rule Assets
	# 望月幽庭勾玉 
	I_HARVEST_JADE_10 = RuleImage(roi_front=(508,529,27,30), roi_back=(508,529,27,30), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main10/harvest_harvest_jade_10.png")
	# 望月幽庭签到 
	I_HARVEST_SIGN_10 = RuleImage(roi_front=(422,532,21,27), roi_back=(422,532,21,27), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main10/harvest_harvest_sign_10.png")
	# 望月幽庭福袋 
	I_HARVEST_SIGN_999_10 = RuleImage(roi_front=(419,538,25,26), roi_back=(419,538,25,26), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main10/harvest_harvest_sign_999_10.png")
	# 望月幽庭食盒 
	I_HARVEST_AP_10 = RuleImage(roi_front=(508,531,25,24), roi_back=(508,531,25,24), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main10/harvest_harvest_ap_10.png")
	# 望月幽庭自选御魂 
	I_HARVEST_SOUL_10 = RuleImage(roi_front=(418,531,27,30), roi_back=(418,531,27,30), threshold=0.8, method="Template matching", file="./tasks/Component/LoginHarvest/main10/harvest_harvest_soul_10.png")


	# Image Rule Assets
	# 缘结神社食盒 
	I_HARVEST_AP_9 = RuleImage(roi_front=(841,488,24,24), roi_back=(718,447,408,147), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main9/harvest_harvest_ap_9.png")
	# 缘结神社999福袋 
	I_HARVEST_SIGN_999_9 = RuleImage(roi_front=(427,491,21,21), roi_back=(267,443,291,145), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main9/harvest_harvest_sign_999_9.png")
	# 缘结神社签到 
	I_HARVEST_SIGN_9 = RuleImage(roi_front=(425,484,26,28), roi_back=(319,452,254,140), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main9/harvest_harvest_sign_9.png")
	# 缘结神社勾玉 
	I_HARVEST_JADE_9 = RuleImage(roi_front=(840,485,25,30), roi_back=(776,452,326,129), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main9/harvest_harvest_jade_9.png")
	# 缘结神社御魂buff 
	I_HARVEST_SOULBUFF_9 = RuleImage(roi_front=(418,480,34,29), roi_back=(307,454,275,135), threshold=0.9, method="Template matching", file="./tasks/Component/LoginHarvest/main9/harvest_harvest_soulbuff_9.png")
	# 缘结神社自选御魂 
	I_HARVEST_SOUL_9 = RuleImage(roi_front=(422,476,33,38), roi_back=(287,452,293,131), threshold=0.8, method="Template matching", file="./tasks/Component/LoginHarvest/main9/harvest_harvest_soul_9.png")


