from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MyOrochiAssets: 


	# Click Rule Assets
	# 结束时的安全点击区域 
	C_SAFE_AREA_1 = RuleClick(roi_front=(32,173,194,390), roi_back=(32,173,194,390), name="safe_area_1")
	# 结束时的安全点击区域2 
	C_SAFE_AREA_2 = RuleClick(roi_front=(1082,187,170,429), roi_back=(1082,187,170,429), name="safe_area_2")


	# Image Rule Assets
	# 第二个坑位标识 
	I_SECOND_PIT_POSITION = RuleImage(roi_front=(597,204,100,100), roi_back=(597,204,100,100), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_second_pit_position.png")
	# 调整按钮 
	I_FIRE_SIGN = RuleImage(roi_front=(1169,603,98,81), roi_back=(1169,603,98,81), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_fire_sign.png")
	# 御魂金币
	I_ORICHI_GLOD = RuleImage(roi_front=(820,182,80,61), roi_back=(0,0,1279,719), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_orichi_glod.png")
	# 魂字标识 
	I_ORICHI_END = RuleImage(roi_front=(574,495,123,102), roi_back=(574,495,123,102), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_orichi_end.png")
	# 太鼓标识 
	I_GU = RuleImage(roi_front=(432,88,100,100), roi_back=(432,88,100,100), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_gu.png")
	# 房间标识 
	I_IN_ROOM = RuleImage(roi_front=(15,524,77,79), roi_back=(15,524,77,79), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_in_room.png")
	# 判断是否进入战斗 
	I_IN_FIGHT = RuleImage(roi_front=(87,17,41,34), roi_back=(87,17,41,34), threshold=0.8, method="Template matching", file="./tasks/MyOrochi/res/res_in_fight.png")


