from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe

# This file was automatically generated by module/dev_tools/assets_extract.py.
# Don't modify it manually.
class CoinChallengeAssets: 

	# Image Rule Assets
	# description 
	I_NEW1 = RuleImage(roi_front=(157,240,70,79), roi_back=(41,185,279,207), threshold=0.8, method="Template matching", file="./tasks/CoinChallenge/res/res_new1.png")
	# description 
	I_NEW2 = RuleImage(roi_front=(362,243,100,100), roi_back=(803,101,100,100), threshold=0.8, method="Template matching", file="./tasks/CoinChallenge/res/res_new2.png")
	# desc55 
	I_NEW3 = RuleImage(roi_front=(568,212,240,220), roi_back=(0,0,100,100), threshold=0.9, method="Template matching", file="./tasks/CoinChallenge/res/res_new3.png")
	# Click Rule Assets
	# description 
	C_NEW1 = RuleClick(roi_front=(268,268,100,100), roi_back=(614,214,100,100), name="new1")
	# description 
	C_NEW2 = RuleClick(roi_front=(171,236,100,100), roi_back=(554,225,100,100), name="new2")
	# desc444n 
	C_NEW3 = RuleClick(roi_front=(180,150,100,100), roi_back=(596,247,100,100), name="new3")
	# Long Click Rule Assets
	# description 
	L_NEW1 = RuleLongClick(roi_front=(208,151,100,100), roi_back=(542,279,100,100), duration=1500, name="new1")
	# description 
	L_NEW2 = RuleLongClick(roi_front=(355,191,100,100), roi_back=(526,323,100,100), duration=1500, name="new2")
	# de66666n 
	L_NEW3 = RuleLongClick(roi_front=(112,156,100,100), roi_back=(469,200,100,100), duration=1000, name="new3")
	# Swipe Rule Assets
	# description 
	S_NEW1 = RuleSwipe(roi_front=(253,212,100,100), roi_back=(652,292,100,100), mode="default", name="new1")
	# description 
	S_NEW2 = RuleSwipe(roi_front=(265,272,100,100), roi_back=(622,338,100,100), mode="default", name="new2")
	# description 
	S_NEW3 = RuleSwipe(roi_front=(198,160,100,100), roi_back=(626,305,100,100), mode="default", name="new3")
	# description 
	S_NEW4 = RuleSwipe(roi_front=(150,145,100,100), roi_back=(535,199,100,100), mode="vector", name="new4")


