from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EvoZoneAssets: 


	# Image Rule Assets
	# 火麒麟进入 
	I_FIRE_KIRIN = RuleImage(roi_front=(104,120,217,325), roi_back=(104,120,217,325), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_fire_kirin.png")
	# 组队 
	I_FORM_TEAM = RuleImage(roi_front=(959,580,100,100), roi_back=(916,572,156,130), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_form_team.png")
	# description 
	I_EVOZONE_LOCK = RuleImage(roi_front=(700,655,31,32), roi_back=(690,648,53,54), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_evozone_lock.png")
	# description 
	I_EVOZONE_UNLOCK = RuleImage(roi_front=(701,657,26,29), roi_back=(695,650,43,45), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_evozone_unlock.png")
	# 点击挑战 
	I_EVOZONE_FIRE = RuleImage(roi_front=(1127,568,131,124), roi_back=(1127,568,131,124), threshold=0.6, method="Template matching", file="./tasks/EvoZone/o/o_evozone_fire.png")
	# 式神录 
	I_SHI_RECORDS = RuleImage(roi_front=(843,570,48,45), roi_back=(843,570,48,45), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_shi_records.png")
	# 小小宠物，发现宝藏 
	I_PET_PRESENT = RuleImage(roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_pet_present.png")
	# 风麒麟进入 
	I_WIND_KIRIN = RuleImage(roi_front=(423,116,201,250), roi_back=(423,116,201,250), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_wind_kirin.png")
	# 水麒麟进入 
	I_WATER_KIRIN = RuleImage(roi_front=(728,115,201,342), roi_back=(728,115,201,342), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_water_kirin.png")
	# 雷麒麟进入 
	I_LIGHTNING_KIRIN = RuleImage(roi_front=(1016,99,218,270), roi_back=(1016,99,218,270), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_lightning_kirin.png")


	# List Rule Assets
	# 这个是觉醒界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/EvoZone/res", direction="vertical", mode="ocr", roi_back=(124,84,77,632), size=(75, 83), 
					 array=["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾"])


	# Ocr Rule Assets
	# Ocr-description 
	O_O_TEST_OCR = RuleOcr(roi=(128,114,349,564), area=(128,114,349,564), mode="Full", method="Default", keyword="", name="o_test_ocr")


