from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GuguArtStudioAssets: 


	# List Rule Assets
	# 前往呱呱画室列表 
	L_GOTO_GUGU_ACT = RuleList(folder="./tasks/GuguArtStudio/gas", direction="vertical", mode="ocr", roi_back=(241,119,49,486), size=(44, 79), 
					 array=["画室"])


	# Image Rule Assets
	# 活动列表页呱呱画室标志 
	I_CHECK_ACT_LIST_GUGU_ACT = RuleImage(roi_front=(577,175,440,117), roi_back=(499,119,595,296), threshold=0.8, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_check_act_list_gugu_act.png")
	# 呱呱画室主页面 
	I_CHECK_GUGU_ACT = RuleImage(roi_front=(1069,20,33,40), roi_back=(1052,10,74,59), threshold=0.7, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_check_gugu_act.png")
	# 获取颜料 
	I_OBTAIN_PAINT = RuleImage(roi_front=(1156,453,51,55), roi_back=(1118,406,156,149), threshold=0.7, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_obtain_paint.png")
	# 提交颜料 
	I_SUBMIT_PAINT = RuleImage(roi_front=(1151,590,58,76), roi_back=(1117,552,148,151), threshold=0.8, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_submit_paint.png")
	# 可以挑战标志 
	I_GAS_CAN_FIRE = RuleImage(roi_front=(1106,578,92,96), roi_back=(1077,548,157,158), threshold=0.8, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_gas_can_fire.png")
	# 前往提交 
	I_GOTO_SUBMIT = RuleImage(roi_front=(694,401,124,62), roi_back=(672,386,165,91), threshold=0.8, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_goto_submit.png")
	# 前往获取 
	I_GOTO_OBTAIN = RuleImage(roi_front=(696,400,126,63), roi_back=(688,391,141,85), threshold=0.8, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_goto_obtain.png")
	# 不能挑战标志 
	I_GAS_CANNOT_FIRE = RuleImage(roi_front=(1100,577,100,100), roi_back=(1078,563,142,128), threshold=0.8, method="Template matching", file="./tasks/GuguArtStudio/gas/gas_gas_cannot_fire.png")


	# Ocr Rule Assets
	# 总颜料 
	O_TOTAL_PAINT = RuleOcr(roi=(1128,25,79,29), area=(1126,23,82,35), mode="Digit", method="Default", keyword="", name="total_paint")
	# 剩余可获得颜料 
	O_REMAIN_GET_PAINT = RuleOcr(roi=(127,591,42,26), area=(124,587,48,32), mode="Digit", method="Default", keyword="", name="remain_get_paint")


